### ISSUE TITLE
Vibrancy package makes atom load up with a white background

### ISSUE THREAD

**Issue by dimitrieh** [simurai/one-vibrancy#11]
@simurai Dark is preferred, is this possible to configure?

**Comment by simurai** [comment]
By default, it changes based on the UI theme, but you can manually switch to dark in the package settings: 

![screen shot 2017-12-02 at 3 58 51 pm](https://user-images.githubusercontent.com/378023/33512824-c46eee94-d779-11e7-9a20-1c73cd321f21.png)
