### ISSUE TITLE
Custom titlebar without vibrancy effect

### ISSUE THREAD

**Issue by 16patsle** [simurai/one-vibrancy#14]
I just noticed that the vibrancy effect does not work on the custom title bar when that is activated. The titlebar has a transparent background instead of a blurry one. I believe this issue might either be caused by the Atom 1.21 update, or related to High Sierra (#13), which in that case might an upstream bug from Electron.

**Comment by simurai** [comment]
I can reproduce this too. I guess it's related to High Sierra. I'll close this as duplicate of #13. Feel free to subscribe there.
