### ISSUE TITLE
This plugin can eat your GPU

### ISSUE THREAD

**Issue by MoOx** [simurai/one-vibrancy#15]
**Note: I know it's not this plugin directly but I just want to share my experience.**

I am using a MacBook 15" (max config, touchbar late 2016) with an external 21" lg ultrafine 4k display.
Until this morning I got no issue with this plugin (with both screens in max-res).

I uninstalled [some drivers](http://www.caldigit.com/support.asp#Uninstaller) (in theory unrelated to my external screen as it's not the same brand) and after the reboot, my GPU was dying. I found that disabling this plugin avoided the 100% GPU issue.
Something is probably wrong with my computer but just in case it happen for other people: your GPU can die depending on your setup.

I will reporting anything as soon as I found the reason about this change.

**Comment by MoOx** [comment]
Just so you know, if this plugin do that, everything that have vibrancy on will do. I just tried native Terminal.app with a few window and GPU is occupied at 100%.
Nothing wrong with this plugin then.

**Comment by simurai** [comment]
@MoOx Thanks for the infos. Yeah, the vibrancy effect could have some performance issues. So it's good to test once in a while.
