### ISSUE TITLE
Does not work properly

### ISSUE THREAD

**Issue by kdnk** [simurai/one-vibrancy#7]
Awosome package! I installed this package to atom 1.19-beta5 but atom seem not to be transparent like following.
<img width="1677" alt="screenshot" src="https://user-images.githubusercontent.com/15260226/28788486-d4637c18-765b-11e7-8735-1eef96fec2d8.png">

The apparence that doesn't use this package is below.

<img width="1679" alt="screenshot" src="https://user-images.githubusercontent.com/15260226/28788504-f40cafc6-765b-11e7-98fc-96aa663e8f6a.png">
Thanks!

**Comment by kdnk** [comment]
I uninstalled all package and try again but apparence is not changed.

**Comment by simurai** [comment]
Just to be sure, how does your desktop background (wallpaper) look like? You might only notice the vibrancy effect if it's not a solid background, otherwise if it's somewhat grey-ish, it could look like in your screenshot.

Could you take another screenshot where the Atom window is a bit smaller so the desktop is also visible?

**Comment by kdnk** [comment]
Screenshot with background.
<img width="1679" alt="screenshot" src="https://user-images.githubusercontent.com/15260226/28810239-ae491f3e-76c3-11e7-9c7d-24269929240d.png">

I tried other background.
<img width="1675" alt="screenshot" src="https://user-images.githubusercontent.com/15260226/28810335-2b9830c4-76c4-11e7-98e0-27413b398b0c.png">

**Comment by simurai** [comment]
Hmm.. yeah, looks like something adds a grey background. Does it work if you paste the following in your [styles.less](http://flight-manual.atom.io/using-atom/sections/basic-customization/#style-tweaks) file?

```less
.one-vibrancy {
  html&,
  body,
  atom-workspace {
      background-color: transparent !important;
  }
}
```

**Comment by kdnk** [comment]
I added to style.less but it seems that background is still grey....

<img width="1675" alt="screenshot" src="https://user-images.githubusercontent.com/15260226/28812204-90af6e00-76ce-11e7-9de2-f3696b120f6e.png">

**Comment by simurai** [comment]
Ha.. very strange. Ok, what about this:

```less
* {
  background: transparent !important;
}
```

It should make every background transparent.

**Comment by kdnk** [comment]
Everything becomes grey.

### one dark theme
<img width="1674" alt="screenshot" src="https://user-images.githubusercontent.com/15260226/28855847-5cd8df06-777a-11e7-8a2c-8848178b5c3b.png">

### one light theme
<img width="1667" alt="screenshot" src="https://user-images.githubusercontent.com/15260226/28855821-265558c4-777a-11e7-9a13-1f551d6c02e2.png">


It might not be correct but I think there is something white background and there seems to be transparent background on it.

**Comment by simurai** [comment]
Ohhh.. you might have the "Reduce transparency" option enabled. If you go to macOS `System Preferences > Accessibility > Display`, make sure to uncheck "Reduce transparency":

![transparency](https://user-images.githubusercontent.com/378023/28859956-5b5fd70e-7795-11e7-9350-26dc7e9351c6.gif)

**Comment by kdnk** [comment]
It works!!!! Thank you very much!!!!!

**Comment by peytonshetler** [comment]
I'm having the same issue as the previous poster?  But I'm following the steps and nothing seems to be working..?  Is this package still being maintained?   Would be so cool to get have a transparent background :)

**Comment by broseiden** [comment]
This is almost good, but still not what I want. Is there any updates on this? I saw this: https://github.com/transcranial/atom-transparency, but seems outdated.
